### ISSUE TITLE
Different Language -> differen no of other languages. 

### ISSUE THREAD

**Issue by ioana-chiorean** [larryhynes/nojpeg#4]
Hi guys, 
Changing between languages will display a different no of available l10n. Check out the screenshots. Is this intended? 

![screenshot 2013-11-05 00 20 31](https://f.cloud.github.com/assets/1391451/1469273/b2a3aef4-459f-11e3-8e71-0f243fd48af7.png)
![screenshot 2013-11-05 00 20 12](https://f.cloud.github.com/assets/1391451/1469272/b2a39e50-459f-11e3-9cfd-5251c6722569.png)
![screenshot 2013-11-05 00 19 56](https://f.cloud.github.com/assets/1391451/1469274/b2a3ee28-459f-11e3-95ab-ac767942dcdb.png)
![screenshot 2013-11-05 00 20 22](https://f.cloud.github.com/assets/1391451/1469275/b2a43ca2-459f-11e3-89e6-17b27eaa442a.png)
![screenshot 2013-11-05 00 20 45](https://f.cloud.github.com/assets/1391451/1469276/b2a7c7fa-459f-11e3-8380-975276e0147b.png)

**Comment by larryhynes** [comment]
Thanks Ioana, this is my fault I haven't been updating the front page of each language section! I'll try to get this fixed today. :o)

**Comment by larryhynes** [comment]
I think I've got it right now - thanks again.
